# Copyright 2025 Bert Haberland
blueprint:
  name: Wjnk Zigbee Dimmer 8-Key Keypad
  description: Links a keypad button/light entity to a target dimmer/light. Triggers On/Off and brightness synchronization.
  domain: automation
  input:
    keypad_light:
      name: Keypad Light Entity
      selector:
        entity:
          domain: light
    target_light:
      name: Target Dimmer/Relay Entity
      selector:
        entity:
          domain:
            - light
            - switch

trigger:
  - platform: state
    entity_id: !input keypad_light
    to: "on"
  - platform: state
    entity_id: !input keypad_light
    to: "off"
  - platform: state
    entity_id: !input keypad_light
    attribute: brightness
    
variables:
  input_target_light: !input target_light

action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.state == 'on' }}"
      sequence:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ (input_target_light | string).startswith('light.') }}"
            sequence:
              - delay:
                  milliseconds: 200
              - service: light.turn_on
                target:
                  entity_id: "{{ input_target_light }}"
                data:
                  brightness: "{{ trigger.to_state.attributes.brightness }}"
                  transition: 0
          - conditions:
            - condition: template
              value_template: "{{ (input_target_light | string).startswith('switch.') }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: "{{ input_target_light }}"

    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.state == 'off' }}"
      sequence:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ (input_target_light | string).startswith('light.') }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: "{{ input_target_light }}"
          - conditions:
            - condition: template
              value_template: "{{ (input_target_light | string).startswith('switch.') }}"
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: "{{ input_target_light }}"

mode: restart